//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XemantiX.Instanciator.SemanticProcessor.Console.SemanticProcessorWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SemanticProcessorWebService.SemanticProcessorWebServiceSoap")]
    public interface SemanticProcessorWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Process", ReplyAction="*")]
        void Process();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SemanticProcessorWebServiceSoapChannel : XemantiX.Instanciator.SemanticProcessor.Console.SemanticProcessorWebService.SemanticProcessorWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SemanticProcessorWebServiceSoapClient : System.ServiceModel.ClientBase<XemantiX.Instanciator.SemanticProcessor.Console.SemanticProcessorWebService.SemanticProcessorWebServiceSoap>, XemantiX.Instanciator.SemanticProcessor.Console.SemanticProcessorWebService.SemanticProcessorWebServiceSoap {
        
        public SemanticProcessorWebServiceSoapClient() {
        }
        
        public SemanticProcessorWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SemanticProcessorWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SemanticProcessorWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SemanticProcessorWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Process() {
            base.Channel.Process();
        }
    }
}
